# Automata n'est pas un service web : il consomme des messages WhatsApp et
# déclenche des tâches planifiées. Le déclarer en "worker" plutôt qu'en "web"
# évite que Dokku attende un port à router et lui applique des vérifications
# HTTP qui échoueraient.
#
# Conséquence : rien n'est exposé publiquement. Le serveur d'observabilité,
# s'il est activé, écoute en loopback dans le conteneur et reste joignable via
# `make dokku-healthcheck`.
#
# Après le premier déploiement :
#   dokku ps:scale automata worker=1
worker: /usr/local/bin/automata -config /config/config.yaml
